import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  overview: [
    {
      type: 'autogenerated',
      dirName: 'index_overview', // '.' 即当前 docs 文件夹
    },
  ],
  spot: [
    {
      type: 'autogenerated',
      dirName: 'spot', // '.' 即当前 docs 文件夹
    },
  ],
  futures: [
    {
      type: 'autogenerated',
      dirName: 'futures', // '.' 即当前 docs 文件夹
    },
  ],
  'margin-spot': [
    {
      type: 'autogenerated',
      dirName: 'margin-spot', // '.' 即当前 docs 文件夹
    },
  ],
  'copy-trading': [
    {
      type: 'autogenerated',
      dirName: 'copy-trading', // '.' 即当前 docs 文件夹
    },
  ],
  'futures-copy': [
    {
      type: 'autogenerated',
      dirName: 'futures-copy', // '.' 即当前 docs 文件夹
    },
  ],
  'trading-third-party': [
    {
      type: 'autogenerated',
      dirName: 'trading-third-party', // '.' 即当前 docs 文件夹
    },
  ],
  'user-center': [
    {
      type: 'autogenerated',
      dirName: 'user-center', // '.' 即当前 docs 文件夹
    },
  ],
  changelog: ['changelog/index'],
  
  // 中文版本侧边栏
  'zh-Hans/overview': [
    {
      type: 'autogenerated',
      dirName: 'overview',
    },
  ],
  'zh-Hans/spot': [
    {
      type: 'autogenerated',
      dirName: 'spot',
    },
  ],
  'zh-Hans/futures': [
    {
      type: 'autogenerated',
      dirName: 'futures',
    },
  ],
  'zh-Hans/margin-spot': [
    {
      type: 'autogenerated',
      dirName: 'margin-spot',
    },
  ],
  'zh-Hans/copy-trading': [
    {
      type: 'autogenerated',
      dirName: 'copy-trading',
    },
  ],
  'zh-Hans/futures-copy': [
    {
      type: 'autogenerated',
      dirName: 'futures-copy',
    },
  ],
  'zh-Hans/trading-third-party': [
    {
      type: 'autogenerated',
      dirName: 'trading-third-party',
    },
  ],
  'zh-Hans/user-center': [
    {
      type: 'autogenerated',
      dirName: 'user-center',
    },
  ],
  'zh-Hans/changelog': ['changelog/index'],
};

export default sidebars;
